name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  # This workflow contains a single job called "build"
  test:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: 
          - 3.7
          - 3.7
          - 3.7
          - 3.5
          - 3.6
          - 3.7
          - 3.8
          - 3.9
        include:
          - python-version: 3.7
            toxenv: black
          - python-version: 3.7
            toxenv: flake8
          - python-version: 3.7
            toxenv: mypy
          - python-version: 3.7
            toxenv: isort
          - python-version: 3.7
            toxenv: black
          - python-version: 3.5
            toxenv: py35
          - python-version: 3.6
            toxenv: py36
          - python-version: 3.7
            toxenv: py37
          - python-version: 3.8
            toxenv: py38
          - python-version: 3.9
            toxenv: py39
    
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
        
      - name: Install Requirements
        run: pip install tox
      
      - name: Run tests
        env:
          TOXENV: ${{ matrix.toxenv }}
        run: tox
      
      - name: Upload coverage to Codecov
        run: |
          pip install coveragepy
          coverage xml
          bash <(curl -s https://codecov.io/bash)
